### ISSUE TITLE
[stack-client] The database used for mime-types is very big

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#109]
Do we need such a big mime type database ?

@goldoraf ?

![image](https://user-images.githubusercontent.com/465582/44577536-ae3b0480-a791-11e8-8c4d-19f5c6ca4958.png)

**Comment by goldoraf** [comment]
Well, yes and no. I had to add this mimetype db because some files' mimetypes are not correctly detected by browsers, especially when drag n' dropping a folder for upload. That leaves us having to guess the mimetype from the file extension, which is the purpose of this lib. But I agree this db is way too large, we could probably build our own with only the more common file types (it'll take some time though). And maybe `cozy-client` isn't the right place to deal with this, we could do it in Drive instead.

**Comment by ptbrowne** [comment]
Mozilla has a pretty good list of mime-types https://developer.mozilla.org/fr/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types

**Comment by y-lohse** [comment]
Hard to say — it looks good, but off the top of my head it lacks HEIC and HEIF types for example.

I don't mind giving this a shot as long as we don't have to do much maintenance on it. If in a couple of month we realize we have to frequently update this list then a reversal might be in order. Does that sound ok ?

**Comment by ptbrowne** [comment]
Yes it sounds OK ;)

**Comment by ptbrowne** [comment]
I am closing and we will reopen if we have problems.
