### ISSUE TITLE
[cozy-client] Use queryConnect with a function that receives ownProps

### ISSUE THREAD

**Issue by drazik** [cozy/cozy-client#314]
This is related to a post on the forum. See https://forum.cozy.io/t/is-it-possible-to-make-a-query-which-is-dependent-upon-props/6236.

The proposition is to make `queryConnect` working with a function that would receives `ownProps` as a parameter, allowing us to make queries based on props using this HOC.

Here is the usage example from the forum:

```js
export default queryConnect(props => ({
  todos: {
    query: entriesQuery.where({ 'list.id': props.routeParams.listID }),
    as: 'todos'
  }
}))(Todos)
```

**Comment by ptbrowne** [comment]
It's already possible to have a query dependent on props, it's almost what you wrote, with the exception that the function is only on the query.

```js
export default queryConnect({
  todos: {
    query: props => entriesQuery.where({ 'list.id': props.routeParams.listID }),
    as: 'todos'
  }
})(Todos)
```

See the code here :

https://github.com/cozy/cozy-client/blob/f0cd4c565a3dc8981e8cba9813adbc256e804769/packages/cozy-client/src/hoc.js#L31

Do you see any advantage for the function form to be supported for the queryConnect options instead of for the query options ?

**Comment by drazik** [comment]
Oh thanks @ptbrowne. Actually I don't see particular advantages. I didn't remember we can do this, and didn't find it quickly in the docs :sweat_smile:. If docs don't exist, I will write it asap.

**Comment by ptbrowne** [comment]
>  If docs don't exist, I will write it asap.

Thanks 💯 !
