### ISSUE TITLE
Improving documentation

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#57]
Watching : https://www.youtube.com/watch?v=azf6yzuJt54 and reading https://www.divio.com/blog/documentation/, there is the advice that documentation should be organized according to 4 different categories : 

- Tutorial (beginner wanting to have a first exposure with the project)
- References (diving deep into the nitty-gritty details)
- How-to guides (I know already about the project, and just want to achieve a task, goal oriented)
- Discussions (technical decisions, architecture etc...)

At first look, it seems a great way to divide things and to approach the good documentation problem. I propose that we use that.

At first for the references : JSDoc could be used to facilitate method documentation ?

[Pad](https://pad.cozycloud.cc/p/ideas-documentation-cozy-client)

**Comment by y-lohse** [comment]
WIP on that in #96 

What is still missing is the automatic update of the doc, and I'm not sure how to best do this.

- Option 1 is that the user does this somehow. But I tried it with a `pre-commit` hook and it didn't seem to work, I still have to investigate why.
- Option 2 would be that travis does this. We could probably make this a part of the publishing process since lerna will make new commits anyway?

Any other ideas on how to best approach this?

**Comment by ptbrowne** [comment]
Option 2 seems good. An approach (untested) :

```bash
if [[ $GIT_BRANCH == "master" ]]; then
	yarn docs
	git status --porcelain # exits with 0 if nothing has changed, 1 otherwise
	
	if [[ ! -z $? ]]; then
	  git add docs/
	  git commit -m 'chore: Update docs'
	  git push origin HEAD
	fi
fi
```

**Comment by kosssi** [comment]
On npm we don't have documentation on packages: https://www.npmjs.com/package/cozy-client

**Comment by y-lohse** [comment]
Right, I guess we have to add a REAME [here](https://github.com/cozy/cozy-client/tree/master/packages/cozy-client).

**Comment by y-lohse** [comment]
This issue is taken over by #105.
