### ISSUE TITLE
When selecting fields, behavior is different between couchdb and pouch

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client#985]
The QueryDefinition has a select() methods that can be used to
restrict the fields that are sent back by couchdb/pouchdb when
fetching documents. This can be used to decrease the size of the
response in order to decrease the response time.

We have a difference between PouchDB and CouchDB here: where
Couchdb will send back the _id of documents regardless of whether
it is included in the select() call, the response of Pouch
will not include it if it is not in the select().

Since the _id is used to index documents in cozy-client's store,
it is important that this field be sent back. If it is not there, after
the response has been entered in the store, the next getQueryFromState
will throw.

On the cozy-client side, we have several choice:

1. Doing nothing, this is the simplest but we rely on users to
  not forget to put "_id" in the selected fields. At least, we could
  mention this in the docs.

2. Issueing a warning when the DSL is used and "_id" is not in
  the fields; "you must add _id to the selected fields for
  cozy client to work correctly". This seems a bit dumb.

3. Automatically adding the _id field when issueing the request
  in the pouch link. It seems like it could be done at this
  layer to be compatible with cozy-client and to have the
  same behavior as the stack link (couchdb).

Do you have any other idea, what do you think ?

**Comment by paultranvan** [comment]
> Couchdb will send back the _id of documents regardless of whether
it is included in the select() call

The [doc](https://docs.couchdb.org/en/2.3.1/api/database/find.html#filtering-fields) says otherwise : 

> Only the specified filter fields are included, in the response. There is no automatic inclusion of the _id or other metadata fields when a field list is included.

I just tested a query on CouchDB that confirms this behaviour. But, after digging, it looks like cozy-stack-client automatically adds the `_id` among other fields: https://github.com/cozy/cozy-client/blob/master/packages/cozy-stack-client/src/DocumentCollection.js#L459

So, that would push for the third choice: do the same in pouch-link

**Comment by ptbrowne** [comment]
Ah, thanks for looking, I had not been that deep :) So yes 3 it seems :)
